title: blog.krashanoff.com
email: lkrashanoff2@gmail.com
description: [mechanical keyboard noises]
baseurl: ""
url: "https://blog.krashanoff.com"
github_username: krashanoff

timezone: America/Los_Angeles

markdown: kramdown
highlighter: rouge
