# Site settings
title: Leo Krashanoff
email: lkrashanoff2@gmail.com
description: ayy lmao
baseurl: "/"
url: "http://about.krashanoff.com"
github_username:  krashanoff

# Build settings
markdown: kramdown
